apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    prometheus: prometheus-operator
    role: alert-rules
    release: prometheus-operator
    {{ include "laa-fee-scheme-api.labels" . | nindent 4 }}
  name: prometheus-custom-rules-{{ .Chart.Name }}
spec:
  groups:
  - name: application-rules
    rules:
    - alert: Instance-Down
      expr: absent(up{namespace="{{ .Release.Namespace }}"}) == 1
      for: 1m
      labels:
        severity: {{ .Values.prometheus.severity }}
      annotations:
        message: Namespace {{"{{"}} $labels.namespace {{"}}"}} is down.
        runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/LFSP/pages/5844631676/Runbook+-+Fee+Scheme+Platform+API
        dashboard_url: {{ .Values.prometheus.dashboardUrl }}
    - alert: KubeQuota-Exceeded
      annotations:
        message: Namespace {{"{{"}} $labels.namespace {{"}}"}} is using {{"{{"}} printf "%0.0f" $value {{"}}"}}% of its {{"{{"}} $labels.resource {{"}}"}} quota.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubequotaexceeded
        dashboard_url: {{ .Values.prometheus.dashboardUrl }}
      expr: |-
        100 * kube_resourcequota{job="kube-state-metrics", type="used", namespace="{{ .Release.Namespace }}"}
        / ignoring(instance, job, type)
        (kube_resourcequota{job="kube-state-metrics", type="hard", namespace="{{ .Release.Namespace }}"} > 0)
        > 90
      for: 15m
      labels:
        severity: {{ .Values.prometheus.severity }}
    - alert: KubePodCrashLooping
      annotations:
        message: Pod {{"{{"}} $labels.namespace {{"}}"}}/{{"{{"}} $labels.pod {{"}}"}} ({{"{{"}} $labels.container {{"}}"}}) is restarting {{"{{"}} printf "%.2f" $value {{"}}"}} times / 5 minutes.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping
        dashboard_url: {{ .Values.prometheus.dashboardUrl }}
      expr: rate(kube_pod_container_status_restarts_total{job="kube-state-metrics", namespace="{{ .Release.Namespace }}"}[15m]) * 60 * 5 > 0
      for: 15m
      labels:
        severity: {{ .Values.prometheus.severity }}
    - alert: KubePodNotReady
      annotations:
        message: Pod {{"{{"}} $labels.namespace {{"}}"}}/{{"{{"}} $labels.pod {{"}}"}} has been in a non-ready state for longer than an hour.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodnotready
        dashboard_url: {{ .Values.prometheus.dashboardUrl }}
      expr: sum by (namespace, pod) (kube_pod_status_phase{job="kube-state-metrics",namespace="{{ .Release.Namespace }}",phase=~"Pending|Unknown"}) > 0
      for: 15m
      labels:
        severity: {{ .Values.prometheus.severity }}
    - alert: KubeDeploymentGenerationMismatch
      annotations:
        message: Deployment generation for {{"{{"}} $labels.namespace {{"}}"}}/{{"{{"}} $labels.deployment{{"}}"}} does not match,
          this indicates that the Deployment has failed but has not been rolled back.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedeploymentgenerationmismatch
        dashboard_url: {{ .Values.prometheus.dashboardUrl }}
      expr: (kube_deployment_status_observed_generation{job="kube-state-metrics", namespace="{{ .Release.Namespace }}"} != kube_deployment_metadata_generation{job="kube-state-metrics", namespace="{{ .Release.Namespace }}"})
      for: 15m
      labels:
        severity: {{ .Values.prometheus.severity }}
    - alert: KubeDeploymentReplicasMismatch
      annotations:
        message: Deployment {{"{{"}} $labels.namespace {{"}}"}}/{{"{{"}} $labels.deployment {{"}}"}} has not matched the expected number of replicas for longer than an hour.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedeploymentreplicasmismatch
        dashboard_url: {{ .Values.prometheus.dashboardUrl }}
      expr: (kube_deployment_spec_replicas{job="kube-state-metrics", namespace="{{ .Release.Namespace }}"} != kube_deployment_status_replicas_available{job="kube-state-metrics", namespace="{{ .Release.Namespace }}"})
      for: 15m
      labels:
        severity: {{ .Values.prometheus.severity }}